version: "3.8"
services:
  mongodb:
    container_name: database_stock_api_test
    image: mongo:7.0
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
      - ./dump:/dump
    environment:
      MONGO_INITDB_DATABASE: stockDatabase
    command: >
      bash -c "
        docker-entrypoint.sh mongod --quiet --logpath /data/db/mongodb.log &
        until mongosh --eval 'db.runCommand({ping:1})' >/dev/null 2>&1; do
          sleep 2;
        done;
        
        # Check if ohlcv_data collection exists and has documents
        if mongosh --quiet --eval 'db.ohlcv_data.countDocuments()' stockDatabase | grep -q '^0$'; then
          echo 'The ohlcv_data collection is empty - performing restore'
          mongorestore /dump
        else
          echo 'The ohlcv_data collection already contains data - skipping restore'
        fi
        
        wait
      "

  app:
    build: .
    ports:
      - 4000:3000
    environment:
      PORT: 3000
      DB_URI: mongodb://mongodb:27017/stockDatabase
    depends_on:
      - mongodb

volumes:
  mongodb: {}
  mongodb-logs:
    driver: local
